#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <ctosapi.h>
#include "../INCLUDES/Define_1.h"
#include "../INCLUDES/Transaction.h"
#include "../INCLUDES/AllStruct.h"
#include "../PRINT/Print.h"
#include "../DISPLAY/Display.h"
#include "../FUNCTION/Function.h"
#include "../FUNCTION/FuncTable.h"
#include "../../NCCC/NCCCtSAM.h"
#include "Flow.h"

extern int	ginDebug;	/* Debug使用 extern */
extern int	ginFindRunTime;

/* 只可刷卡，不開晶片 */
int SALE_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_FUNCTION_GET_CARD_FIELDS_,
	_NCCC_FUNCTION_CHECK_SPECIALCARD_IN_OPT_FLOW_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_ ,
};

/* 可刷卡、也可插卡 */
int SALE_ICC_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_FUNCTION_GET_CARD_FIELDS_ICC_,
	_NCCC_FUNCTION_CHECK_SPECIALCARD_IN_OPT_FLOW_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_ ,
};

int SALE_CTLS_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_NCCC_FUNCTION_CHECK_IS_TICKET_PURCHASE_,
        _NCCC_FUNCTION_GET_PDS0523_,
	_NCCC_FUNCTION_GET_PDS0524_,
	_NCCC_FUNCTION_GET_TXN_CATEGORY_,
	_NCCC_FUNCTION_GET_PDS0530_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_NCCC_FUNCTION_GET_OPT_PAY_ITEM_,
	_FUNCTION_GET_CARD_FIELDS_CTLS_,
	_NCCC_FUNCTION_CHECK_SPECIALCARD_IN_OPT_FLOW_,
	_NCCC_FUNCTION_CL_POWER_OFF_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_ ,
};

int SALE_CTLS_IDLE_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_FUNCTION_IDLE_CHECKCUSTOMPASSWORD_FLOW_,
	_CREDIT_FUNCTION_GET_OPT_AMOUNT_,
	_NCCC_FUNCTION_CHECK_IS_TICKET_PURCHASE_,
        _NCCC_FUNCTION_GET_PDS0523_,
	_NCCC_FUNCTION_GET_PDS0524_,
	_NCCC_FUNCTION_GET_TXN_CATEGORY_,
	_NCCC_FUNCTION_GET_PDS0530_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_NCCC_FUNCTION_GET_OPT_PAY_ITEM_,
	_FUNCTION_GET_CARD_FIELDS_CTLS_,
	_NCCC_FUNCTION_CHECK_SPECIALCARD_IN_OPT_FLOW_,
	_NCCC_FUNCTION_CL_POWER_OFF_,		/* 電票不能關天線 */
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_ ,
};

/* (需求單-109455)-Üny實體掃碼需求 by Russell 2021/9/10 上午 10:32 */
int SALE_BARCODE_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_CREDIT_FUNCTION_GET_OPT_AMOUNT_,
	_NCCC_FUNCTION_CHECK_IS_TICKET_PURCHASE_,
        _NCCC_FUNCTION_GET_PDS0523_,
	_NCCC_FUNCTION_GET_PDS0524_,
	_NCCC_FUNCTION_GET_TXN_CATEGORY_,
	_NCCC_FUNCTION_GET_PDS0530_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_NCCC_FUNCTION_GET_OPT_PAY_ITEM_,
	_FUNCTION_GET_CARD_FIELDS_CTLS_,
	_NCCC_FUNCTION_CHECK_SPECIALCARD_IN_OPT_FLOW_,
	_NCCC_FUNCTION_CL_POWER_OFF_,		/* 電票不能關天線 */
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_ ,
};

int FISC_SALE_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_FUNCTION_GET_CARD_FIELDS_FISC_,
	_NCCC_FUNCTION_CHECK_SPECIALCARD_IN_OPT_FLOW_,
	_FLOW_NULL_,
};

int FISC_SALE_CTLS_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_FUNCTION_GET_CARD_FIELDS_FISC_CTLS_,
	_NCCC_FUNCTION_CHECK_SPECIALCARD_IN_OPT_FLOW_,
	_NCCC_FUNCTION_CL_POWER_OFF_,
	_FLOW_NULL_,
};

int INST_SALE_CTLS_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_PERIOD_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_NCCC_FUNCTION_GET_OPT_PAY_ITEM_,
	_FUNCTION_GET_CARD_FIELDS_CTLS_,
	_NCCC_FUNCTION_CHECK_SPECIALCARD_IN_OPT_FLOW_,
	_NCCC_FUNCTION_CL_POWER_OFF_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_ ,
};

/* (需求單-109455)-Üny實體掃碼需求 by Russell 2021/9/10 上午 10:32 */
int INST_SALE_BARCODE_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_PERIOD_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_NCCC_FUNCTION_GET_OPT_PAY_ITEM_,
	_FUNCTION_GET_CARD_FIELDS_CTLS_,
	_NCCC_FUNCTION_CHECK_SPECIALCARD_IN_OPT_FLOW_,
	_NCCC_FUNCTION_CL_POWER_OFF_,		/* 電票不能關天線 */
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_ ,
};

int INST_REFUND_CTLS_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_CREDIT_FUNCTION_GET_OPT_REFUND_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_PERIOD_,
	_CREDIT_FUNCTION_GET_OPT_DOWNPAYMENT_,
	_CREDIT_FUNCTION_GET_OPT_INSTPAYMENT_,
	_CREDIT_FUNCTION_GET_OPT_AUTHCODE_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_NCCC_FUNCTION_GET_OPT_PAY_ITEM_,
	_FUNCTION_GET_CARD_FIELDS_REFUND_CTLS_FLOW_,
	_NCCC_FUNCTION_CHECK_SPECIALCARD_IN_OPT_FLOW_,
	_NCCC_FUNCTION_CL_POWER_OFF_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_ ,
};

/* (需求單-109455)-Üny實體掃碼需求 by Russell 2021/9/10 上午 10:32 */
int INST_REFUND_BARCODE_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_CREDIT_FUNCTION_GET_OPT_REFUND_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_PERIOD_,
	_CREDIT_FUNCTION_GET_OPT_DOWNPAYMENT_,
	_CREDIT_FUNCTION_GET_OPT_INSTPAYMENT_,
	_CREDIT_FUNCTION_GET_OPT_AUTHCODE_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_NCCC_FUNCTION_GET_OPT_PAY_ITEM_,
	_FUNCTION_GET_CARD_FIELDS_REFUND_CTLS_FLOW_,
	_NCCC_FUNCTION_CHECK_SPECIALCARD_IN_OPT_FLOW_,
	_NCCC_FUNCTION_CL_POWER_OFF_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_ ,
};

int INST_ADJUST_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_FUNCTION_GET_CARD_FIELDS_FLOW_,
	_NCCC_FUNCTION_CHECK_SPECIALCARD_IN_OPT_FLOW_,
	_NCCC_FUNCTION_CL_POWER_OFF_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_ ,
};

int INST_ADJUST_CTLS_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_PERIOD_,
	_CREDIT_FUNCTION_GET_OPT_DOWNPAYMENT_,
	_CREDIT_FUNCTION_GET_OPT_INSTPAYMENT_,
	_CREDIT_FUNCTION_GET_OPT_AUTHCODE_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_FUNCTION_GET_CARD_FIELDS_CTLS_,
	_NCCC_FUNCTION_CHECK_SPECIALCARD_IN_OPT_FLOW_,
	_NCCC_FUNCTION_CL_POWER_OFF_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_ ,
};

int REDEEM_SALE_CTLS_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_NCCC_FUNCTION_GET_OPT_PAY_ITEM_,
	_FUNCTION_GET_CARD_FIELDS_CTLS_,
	_NCCC_FUNCTION_CHECK_SPECIALCARD_IN_OPT_FLOW_,
	_NCCC_FUNCTION_CL_POWER_OFF_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_ ,
};

/* (需求單-109455)-Üny實體掃碼需求 by Russell 2021/9/10 上午 10:32 */
int REDEEM_SALE_BARCODE_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_NCCC_FUNCTION_GET_OPT_PAY_ITEM_,
	_FUNCTION_GET_CARD_FIELDS_CTLS_,
	_NCCC_FUNCTION_CHECK_SPECIALCARD_IN_OPT_FLOW_,
	_NCCC_FUNCTION_CL_POWER_OFF_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_ ,
};

int REDEEM_REFUND_CTLS_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_CREDIT_FUNCTION_GET_OPT_REFUND_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_PAY_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_REDEEM_POINT_,
	_CREDIT_FUNCTION_GET_OPT_AUTHCODE_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_NCCC_FUNCTION_GET_OPT_PAY_ITEM_,
	_FUNCTION_GET_CARD_FIELDS_REFUND_CTLS_FLOW_,
	_NCCC_FUNCTION_CHECK_SPECIALCARD_IN_OPT_FLOW_,
	_NCCC_FUNCTION_CL_POWER_OFF_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_ ,
};

/* (需求單-109455)-Üny實體掃碼需求 by Russell 2021/9/10 上午 10:32 */
int REDEEM_REFUND_BARCODE_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_CREDIT_FUNCTION_GET_OPT_REFUND_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_PAY_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_REDEEM_POINT_,
	_CREDIT_FUNCTION_GET_OPT_AUTHCODE_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_NCCC_FUNCTION_GET_OPT_PAY_ITEM_,
	_FUNCTION_GET_CARD_FIELDS_REFUND_CTLS_FLOW_,
	_NCCC_FUNCTION_CHECK_SPECIALCARD_IN_OPT_FLOW_,
	_NCCC_FUNCTION_CL_POWER_OFF_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_ ,
};

int REDEEM_ADJUST_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_FUNCTION_GET_CARD_FIELDS_FLOW_,
	_NCCC_FUNCTION_CHECK_SPECIALCARD_IN_OPT_FLOW_,
	_NCCC_FUNCTION_CL_POWER_OFF_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_ ,
};

int REDEEM_ADJUST_CTLS_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_PAY_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_REDEEM_POINT_,
	_CREDIT_FUNCTION_GET_OPT_AUTHCODE_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_FUNCTION_GET_CARD_FIELDS_CTLS_,
	_NCCC_FUNCTION_CHECK_SPECIALCARD_IN_OPT_FLOW_,
	_NCCC_FUNCTION_CL_POWER_OFF_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_ ,
};

int VOID_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_FUNCTION_GET_HOST_NUM_FLOW_,
	_FUNCTION_USER_CHOICE_,
	_HG_FUNCTION_SELECT_VOID_TRT_,
	_FLOW_NULL_ ,
};

int REFUND_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_FUNCTION_GET_CARD_FIELDS_FLOW_,
	_NCCC_FUNCTION_CHECK_SPECIALCARD_IN_OPT_FLOW_,
	_NCCC_FUNCTION_CL_POWER_OFF_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_ ,
};

int REFUND_AMOUNT_FIRST_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_CREDIT_FUNCTION_GET_OPT_REFUND_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_AUTHCODE_,
	_NCCC_FUNCTION_CHECK_IS_TICKET_PURCHASE_,
	_NCCC_FUNCTION_GET_PDS0523_,
	_NCCC_FUNCTION_GET_PDS0524_,
	_NCCC_FUNCTION_GET_TXN_CATEGORY_,
	_NCCC_FUNCTION_GET_PDS0530_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_NCCC_FUNCTION_GET_OPT_PAY_ITEM_,
	_FUNCTION_GET_CARD_FIELDS_FLOW_,
	_NCCC_FUNCTION_CHECK_SPECIALCARD_IN_OPT_FLOW_,
	_NCCC_FUNCTION_CL_POWER_OFF_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_ ,
};

int REFUND_CTLS_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_CREDIT_FUNCTION_GET_OPT_REFUND_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_AUTHCODE_,
	_NCCC_FUNCTION_CHECK_IS_TICKET_PURCHASE_,
	_NCCC_FUNCTION_GET_PDS0523_,
	_NCCC_FUNCTION_GET_PDS0524_,
	_NCCC_FUNCTION_GET_TXN_CATEGORY_,
	_NCCC_FUNCTION_GET_PDS0530_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_NCCC_FUNCTION_GET_OPT_PAY_ITEM_,
	_FUNCTION_GET_CARD_FIELDS_REFUND_CTLS_FLOW_,
	_NCCC_FUNCTION_CHECK_SPECIALCARD_IN_OPT_FLOW_,
	_NCCC_FUNCTION_CL_POWER_OFF_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_ ,
};

int REFUND_AMOUNT_FIRST_CUP_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_CREDIT_FUNCTION_GET_OPT_REFUND_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_ORI_TRANSDATE_,
	_CREDIT_FUNCTION_GET_OPT_AUTHCODE_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_NCCC_FUNCTION_GET_OPT_PAY_ITEM_,
	_FUNCTION_GET_CARD_FIELDS_FLOW_,
	_NCCC_FUNCTION_CHECK_SPECIALCARD_IN_OPT_FLOW_,
	_NCCC_FUNCTION_CL_POWER_OFF_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_ ,
};

int REFUND_CTLS_CUP_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_CREDIT_FUNCTION_GET_OPT_REFUND_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_ORI_TRANSDATE_,
	_CREDIT_FUNCTION_GET_OPT_AUTHCODE_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_NCCC_FUNCTION_GET_OPT_PAY_ITEM_,
	_FUNCTION_GET_CARD_FIELDS_REFUND_CTLS_FLOW_,
	_NCCC_FUNCTION_CHECK_SPECIALCARD_IN_OPT_FLOW_,
	_NCCC_FUNCTION_CL_POWER_OFF_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_ ,
};

/* 復刻板，先過卡退貨感應流程 */
int REFUND_CTLS_GET_CARD_FIRST_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_FUNCTION_GET_CARD_FIELDS_REFUND_CTLS_FLOW_,
	_NCCC_FUNCTION_CHECK_SPECIALCARD_IN_OPT_FLOW_,
	_NCCC_FUNCTION_CL_POWER_OFF_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_ ,
};

/* (需求單-109455)-Üny實體掃碼需求 by Russell 2021/9/10 上午 10:32 */
int REFUND_BARCODE_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_CREDIT_FUNCTION_GET_OPT_REFUND_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_AUTHCODE_,
	_NCCC_FUNCTION_CHECK_IS_TICKET_PURCHASE_,
	_NCCC_FUNCTION_GET_PDS0523_,
	_NCCC_FUNCTION_GET_PDS0524_,
	_NCCC_FUNCTION_GET_TXN_CATEGORY_,
	_NCCC_FUNCTION_GET_PDS0530_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_NCCC_FUNCTION_GET_OPT_PAY_ITEM_,
	_FUNCTION_GET_CARD_FIELDS_REFUND_CTLS_FLOW_,
	_NCCC_FUNCTION_CHECK_SPECIALCARD_IN_OPT_FLOW_,
	_NCCC_FUNCTION_CL_POWER_OFF_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_ ,
};

int FISC_REFUND_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_FUNCTION_GET_CARD_FIELDS_FISC_,
	_NCCC_FUNCTION_CHECK_SPECIALCARD_IN_OPT_FLOW_,
	_NCCC_FUNCTION_CL_POWER_OFF_,
	_CREDIT_FUNCTION_GET_OPT_FISC_ORI_TRANSDATE_,
	_CREDIT_FUNCTION_GET_OPT_FISC_RRN_,
	_CREDIT_FUNCTION_GET_OPT_FISC_REFUND_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_FLOW_NULL_,
};

int FISC_REFUND_CTLS_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_CREDIT_FUNCTION_GET_OPT_FISC_ORI_TRANSDATE_,
	_CREDIT_FUNCTION_GET_OPT_FISC_RRN_,
	_CREDIT_FUNCTION_GET_OPT_FISC_REFUND_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_FUNCTION_GET_CARD_FIELDS_FISC_REDEND_CTLS_,
	_NCCC_FUNCTION_CHECK_SPECIALCARD_IN_OPT_FLOW_,
	_NCCC_FUNCTION_CL_POWER_OFF_,
	_FLOW_NULL_,
};

int SETTLE_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_BDAU_SETTLEMENT_CHECK_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_FUNCTION_GET_HOST_NUM_FLOW_,
        _FUNCTION_PREPRINT_REPORT_BY_BUFFER_,
	_CREDIT_FUNCTION_CHECK_RESULT_SETTLE_,
	_FLOW_NULL_ ,
};

int TIP_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_FUNCTION_GET_HOST_NUM_FLOW_,
	_FUNCTION_USER_CHOICE_,
	_FLOW_NULL_ ,
};

int SALE_OFFLINE_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_FUNCTION_GET_CARD_FIELDS_FLOW_,
	_NCCC_FUNCTION_CHECK_SPECIALCARD_IN_OPT_FLOW_,
	_NCCC_FUNCTION_CL_POWER_OFF_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_ ,
};

int SALE_OFFLINE_CTLS_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_NCCC_FUNCTION_GET_OPT_PAY_ITEM_,
	_FUNCTION_GET_CARD_FIELDS_CTLS_,
	_NCCC_FUNCTION_CHECK_SPECIALCARD_IN_OPT_FLOW_,
	_NCCC_FUNCTION_CL_POWER_OFF_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_ ,
};

int ADJUST_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_FUNCTION_GET_HOST_NUM_FLOW_,
	_FUNCTION_USER_CHOICE_,
	_FLOW_NULL_ ,
};

int PRE_AUTH_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_FUNCTION_GET_CARD_FIELDS_ICC_,
	_NCCC_FUNCTION_CHECK_SPECIALCARD_IN_OPT_FLOW_,
	_NCCC_FUNCTION_CL_POWER_OFF_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_ ,
};

int PRE_AUTH_CTLS_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_NCCC_FUNCTION_GET_OPT_PAY_ITEM_,
	_FUNCTION_GET_CARD_FIELDS_CTLS_,
	_NCCC_FUNCTION_CHECK_SPECIALCARD_IN_OPT_FLOW_,
	_NCCC_FUNCTION_CL_POWER_OFF_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_ ,
};

int PRE_COMP_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_FUNCTION_GET_CARD_FIELDS_FLOW_,
	_NCCC_FUNCTION_CHECK_SPECIALCARD_IN_OPT_FLOW_,
	_NCCC_FUNCTION_CL_POWER_OFF_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_ ,
};

int PRE_COMP_CTLS_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_CREDIT_FUNCTION_GET_OPT_ORI_TRANSDATE_,
	_CREDIT_FUNCTION_GET_OPT_AUTHCODE_,
	_CREDIT_FUNCTION_GET_OPT_ORI_PREAUTH_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_PRECOMP_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_NCCC_FUNCTION_GET_OPT_PAY_ITEM_,
	_FUNCTION_GET_CARD_FIELDS_REFUND_CTLS_FLOW_,
	_NCCC_FUNCTION_CHECK_SPECIALCARD_IN_OPT_FLOW_,
	_NCCC_FUNCTION_CL_POWER_OFF_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_FLOW_NULL_ ,
};

int MAIL_ORDER_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_FUNCTION_GET_CREDIT_CARD_FIELDS_MAIL_ORDER_,
	_NCCC_FUNCTION_CHECK_SPECIALCARD_IN_OPT_FLOW_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_CREDIT_FUNCTION_GET_CVV2_,
	_FLOW_NULL_ ,
};

int LOYALTY_REDEEM_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_FUNCTION_GET_CARD_FIELDS_LOYALTY_REDEEM_,
	_NCCC_FUNCTION_CHECK_SPECIALCARD_IN_OPT_FLOW_,
	_NCCC_FUNCTION_CL_POWER_OFF_,
	_FUNCTION_CHECK_PAN_EXPDATE_LOYALTY_REDEEM_,
	_FLOW_NULL_ ,
};

int LOYALTY_REDEEM_CTLS_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_FUNCTION_GET_CARD_FIELDS_LOYALTY_REDEEM_CTLS_,
	_NCCC_FUNCTION_CHECK_SPECIALCARD_IN_OPT_FLOW_,
	_NCCC_FUNCTION_CL_POWER_OFF_,
	_FUNCTION_CHECK_PAN_EXPDATE_LOYALTY_REDEEM_,
	_FLOW_NULL_ ,
};

int BARCODE_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_FUNCTION_GET_BARCODE_,
	_FUNCTION_CHECK_BARCODE_LOYALTY_REDEEM_,
	_FLOW_NULL_ ,
};

int VOID_LOYALTY_REDEEM_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_FUNCTION_GET_BARCODE_,
	_FUNCTION_CHECK_BARCODE_LOYALTY_REDEEM_,
	_FLOW_NULL_ ,
};

int PRINT_TOTAL_OPERATION_BY_BUFFER_TABLE[] =
{
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,	/* 立即回傳 */
        _NCCC_FUNCTION_SEND_ECR_AFTER_PRINT_RECEIPT_,
	_FUNCTION_GET_HOST_NUM_FLOW_,
	_NCCC_FUNCTION_AUTO_PRINT_TOTAL_REPORT_FLOW_,
	_FLOW_NULL_,
};

int PRINT_DETAIL_OPERATION_BY_BUFFER_TABLE[] =
{
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,	/* 立即回傳 */
        _NCCC_FUNCTION_SEND_ECR_AFTER_PRINT_RECEIPT_,
	_FUNCTION_GET_HOST_NUM_FLOW_,
	_NCCC_FUNCTION_AUTO_PRINT_DETAIL_REPORT_FLOW_,
	_FLOW_NULL_,
};

int DELETE_BATCH_OPERATION_TABLE[] =
{
	_FUNCTION_GET_HOST_NUM_FLOW_,
	_NCCC_FUNCTION_OPT_DELETE_BATCH_CUSTOMER_FLOW_,
	_FUNCTION_REST_BATCH_INV_,
	_FUNCTION_UPDATE_BATCH_NUM_,
        _NCCC_FUNCTION_SETTLEMENT_XML_NCCC_END_,
	_FLOW_NULL_,
};

int PRINT_PARAM_TERM_BYBUFFER_TABLE[] =
{
	_CREDIT_FUNCTION_PRINT_PARAM_TERM_BY_BUFFER_,
	_FLOW_NULL_,
};

int PRINT_DCC_PARAM_TERM_BYBUFFER_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_CREDIT_FUNCTION_PRINT_DCC_PARAM_BY_BUFFER_,
	_FLOW_NULL_,
};

int SIGNPAD_TEST_TABLE[] =
{
	_FUNCTION_GET_SIGNPAD_,
	_FLOW_NULL_,
};

int FUN5_TMS_DOWNLOAD_TABLE[] =
{
	_NCCC_FUNCTION_All_HOST_MUST_SETTLE_FLOW_,
	_FUNC5_TMS_SELECT_FLOW_,
	_NCCC_FUNCTION_UPDATE_PEM_BEFORE_TMS_MANUAL_DOWNLOAD_,
	_FUNCTION_TMS_CONNECT_,
	_FUNCTION_TMS_SEND_RECEIVE_FLOW_,
	_FUNCTION_TMS_RESULT_HANDLE_,
	_FUNCTION_TMS_DISCONNECT_,
	_FUNCTION_TMS_REBOOT_,
	_FLOW_NULL_,
};

int FUN5_RETURN_TASK_REPORT_TABLE[] =
{
	_NCCC_FUNCTION_All_HOST_MUST_SETTLE_FLOW_,
	_FUNC5_TASK_REPORT_,
	_FUNCTION_TMS_CONNECT_,
	_FUNCTION_TMS_SEND_RECEIVE_,
	_FUNCTION_TMS_PRINT_RETURN_TASK_,
	_FUNCTION_TMS_DISCONNECT_,
	_FLOW_NULL_,
};

int FUN5_DCC_DOWNLOAD_TABLE[]=
{
	_FUNC5_DCC_DOWNLOAD_PARAMETER_,
	_FLOW_NULL_,
};

int FUN6_TMS_DOWNLOAD_TABLE[] =
{
	_NCCC_FUNCTION_All_HOST_MUST_SETTLE_FLOW_,
	_FUN6_TMS_DOWNLOAD_,
	_NCCC_FUNCTION_UPDATE_PEM_BEFORE_TMS_MANUAL_DOWNLOAD_,
	_FUNCTION_TMS_CONNECT_,
	_FUNCTION_TMS_SEND_RECEIVE_FLOW_,
	_FUNCTION_TMS_RESULT_HANDLE_,
	_FUNCTION_TMS_DISCONNECT_,
	_FUNCTION_TMS_REBOOT_,
	_FLOW_NULL_,	
};

int FUN6_TMS_TRACELOG_UPLOAD_TABLE[] =
{
	_FUN6_TRACELOG_UPLOAD_,
	_FUNCTION_TMS_CONNECT_,
	_FUNCTION_TMS_SEND_RECEIVE_,
	_FUNCTION_TMS_DISCONNECT_,
	_FLOW_NULL_,
};

int FUNC_TMS_TRACELOG_PRINT_TABLE[] =
{
	_CREDIT_FUNCTION_PRINT_TERMINAL_TRACE_LOG_,
	_FLOW_NULL_,
};

int FUN6_DCC_DOWNLOAD_TABLE[]=
{
	_FUNC5_DCC_DOWNLOAD_PARAMETER_,
	_FLOW_NULL_,
};

int FUN6_DCC_RATE_DOWNLOAD_TABLE[]=
{
	_NCCC_DCC_FUNCTION_EXCHANGE_RATE_DOWNLOAD_,
	_FLOW_NULL_,
};

/* NCCC tSAM 註冊 */
int TSAM_OPERATION_TABLE[] =
{
	_NCCC_FUNCTION_SHOW_REGISTER_MENU_,
	_FLOW_NULL_,
};

/* 交易查詢 */
int REVIEW_OPRATION_TABLE[] =
{
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,	/* 立即回傳 */
        _NCCC_FUNCTION_SEND_ECR_AFTER_PRINT_RECEIPT_,
	_FUNCTION_GET_HOST_NUM_FLOW_,
	_FUNCTION_REVIEW_,
	_FLOW_NULL_,
};

/* 總額查詢 */
int REVIEW_TOTAL_OPRATION_TABLE[] =
{
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,	/* 立即回傳 */
        _NCCC_FUNCTION_SEND_ECR_AFTER_PRINT_RECEIPT_,
	_FUNCTION_GET_HOST_NUM_FLOW_,
	_FUNCTION_TOTAL_REVIEW_,
	_FLOW_NULL_,
};

/* 明細查詢 */
int REVIEW_DETAIL_OPRATION_TABLE[] =
{
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,	/* 立即回傳 */
        _NCCC_FUNCTION_SEND_ECR_AFTER_PRINT_RECEIPT_,
	_FUNCTION_GET_HOST_NUM_FLOW_,
	_FUNCTION_DETAIL_REVIEW_NEWUI_,
	_FLOW_NULL_,
};

/* 重印帳單 */
int REPRINT_OPERATION_TABLE[] =
{
	_NCCC_FUNCTION_REPRINT_CUSTOMER_FLOW_,
	_FLOW_NULL_,
};

/* 重印帳單標準 */
int REPRINT_NORMAL_OPERATION_TABLE[] =
{
	_FUNCTION_GET_HOST_NUM_FLOW_,
	_FUNCTION_USER_CHOICE_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
        _NCCC_FUNCTION_SEND_ECR_AFTER_PRINT_RECEIPT_,
	_FUNCTION_REPRINT_RECEIPT_BY_BUFFER_,
	_FLOW_NULL_,
};

int FUN1_READERINIT_TABLE[] =
{
	_CTLS_INIT_,
	_FLOW_NULL_,
};

/* ECR連線 */
int ECR_TRANSACTION_TABLE[] =
{	
	_FUNCTION_ECR_RECEIVE_TRANSACTION_REQUEST_,
	_FUNCTION_ECR_CHOOSE_WAY_,
	_FLOW_NULL_,
};

/* 一般ECR連線 */
int ECR_TRANSACTION_NORMAL_TABLE[] =
{	
	_FUNCTION_ECR_CUSTOMER_FLOW_,
	_FUNCTION_ECR_NO_TRT_RETURN_FLOW_,
	_FLOW_NULL_,
};

/* IPASS_Reader */
int IPASS_READER_TABLE[] =
{	
	_FUNCTION_ECR_CUS_096_IPASS_TRANSACTION_FLOW_,
	_FLOW_NULL_,
};

/* 當外接設備 */
int MULTIFUNC_SLAVE_TRANSACTION_TABLE[] =
{	
	_MULTIFUNC_RC_COMMAND_,
	_MULTIFUNC_SEND_RESULT_,
	_FLOW_NULL_,
};

/* ESC IDLE 上傳 */
int ESC_UPLOAD_IDLE_TABLE[] =
{	
	_NCCC_ESC_UPLOAD_IDLE_,
	_FLOW_NULL_,
};

/* DCC 排程下載 */
int DCC_SCHEDULE_TABLE[] = 
{
	_NCCC_DCC_AUTO_DOWNLOAD_,
	_FLOW_NULL_,
};

/* TMS連動DCC下載 */
int TMS_DCC_SCHEDULE[] =
{
	_NCCC_DCC_TMS_SCHEDULE_,
	_FLOW_NULL_,
};

/* DCC整點提示下載 */
int DCC_HOUR_NOTIFY[] =
{
	_NCCC_DCC_HOUR_NOTIFY_,
	_FLOW_NULL_,
};

/* TMS排程詢問 */
int TMS_SCHEDULE_INQUIRE_TABLE[] =
{
	_FUNCTION_TMS_SCHEDULE_INQUIRE_,
	_FLOW_NULL_,
};

/* TMS排程下載 */
int TMS_SCHEDULE_DOWNLOAD_TABLE[] =
{
	_FUNCTION_TMS_SCHEDULE_DOWNLOAD_,
	_FUNCTION_TMS_REBOOT_,
	_FLOW_NULL_,
};

/* TMS參數生效 */
int TMS_PROCESS_EFFECTIVE_TABLE[] =
{
	_FUNCTION_All_HOST_MUST_SETTLE_,
	_FUNCTION_TMS_IDLE_UPDATE_,
	_FLOW_NULL_,
};

/* HAPPYGO */
int HG_OPERATION_TABLE[] = 
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_GET_CARD_FIELDS_HG_,
	_FUNCTION_CHECK_HG_PAN_EXPDATE_,
	_HG_FUNCTION_SELECT_PAYMENT_TYPE_,	/* 在此輸入密碼 */
	_FUNCTION_GET_CREDIT_CARD_FIELDS_HG_,
	_NCCC_FUNCTION_CHECK_SPECIALCARD_IN_OPT_FLOW_,
	_NCCC_FUNCTION_CL_POWER_OFF_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_HG_FUNCTION_SELECT_HOST_TRT_,
	_FLOW_NULL_,
};

int HG_REFUND_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_FUNCTION_GET_CARD_FIELDS_HG_,
	_NCCC_FUNCTION_CL_POWER_OFF_,
	_HG_FUNCTION_SELECT_PAYMENT_REFUND_,
	_FUNCTION_CHECK_HG_PAN_EXPDATE_,
	_HG_FUNCTION_SELECT_HOST_TRT_,
	_FLOW_NULL_,
};

int HG_I_R_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_HG_FUNCTION_SELECT_TRANS_TYPE_,
	_HG_FUNCTION_SELECT_I_R_PAYMENT_TYPE_,
	_FLOW_NULL_,
};

int HG_INST_SALE_CTLS_OPERATION_TABLE[] = 
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_PERIOD_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_FUNCTION_GET_CREDIT_CARD_FIELDS_HG_,
	_NCCC_FUNCTION_CHECK_SPECIALCARD_IN_OPT_FLOW_,
	_NCCC_FUNCTION_CL_POWER_OFF_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_HG_FUNCTION_SELECT_HOST_TRT_,
	_FLOW_NULL_ ,
};

int HG_REDEEM_SALE_CTLS_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_NCCC_FUNCTION_CHECK_TXN_FUNCTION_WHEN_ECR_,
	_FUNCTION_ECR_CHECKCUSTOMPASSWORD_FLOW_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_FUNCTION_GET_CREDIT_CARD_FIELDS_HG_,
	_NCCC_FUNCTION_CHECK_SPECIALCARD_IN_OPT_FLOW_,
	_NCCC_FUNCTION_CL_POWER_OFF_,
	_FUNCTION_CHECK_PAN_EXPDATE_,
	_HG_FUNCTION_SELECT_HOST_TRT_,
	_FLOW_NULL_ ,
};

/* BOOTING 開機流程 */
int EDC_BOOTING_TABLE[] =
{	
	_EDC_BOOTING_GET_EDC_BOOT_TIME_,	/* 取得EDC開機時間 */  /*2019/2/27 上午 10:57 Added by Hachi*/
	_EDC_BOOTING_DISPLAY_INITIAL_,		/* 顯示函式庫初始化 */
	_EDC_BOOTING_PRINT_INITIAL_,		/* 列印函式庫初始化(要印電票啟用通知，所以原地方再加回來)2020/6/29 上午 11:40 by Russell */
	_EDC_BOOTING_CASTLE_LIBRARY_INITIAL_,	/* 虹堡函式庫初始化 */
        _EDC_BOOTING_SQLITE_INITIAL_,		/* SQLite初始化 */
        _EDC_BOOTING_XML_LIB_INIT_,             /* XML lib及global variable初始化 */
	_EDC_BOOTING_SYNC_DEBUG_,		/* 同步Debug Flag */
	_EDC_BOOTING_TMS_AP_UPDATE_RECHECK_OK_,	/* 若AP更新非正常流程重開機補救機制 */
	_EDC_BOOTING_UPDATE_PARAMETER_POWER_ON_,/* 檢查是否需更新 */
	_EDC_BOOTING_UI_INITIAL_,		/* 初始化解壓縮UI圖檔 */
	_EDC_BOOTING_SET_BRIGHTNESS_,		/* 設定亮度 */
	_EDC_BOOTING_PRINT_INITIAL_,		/* 列印函式庫初始化(會參考CFGT，移至更新參數後面)2019/10/22 下午 5:05 by Russell */
	_EDC_BOOTING_SET_CASTLE_PWD_,		/* 設定進入系統模式的密碼 */
	_EDC_BOOTING_SET_SYSTEM_POWER_FUNCTION_,/* 設定是否可使用電源鍵 */
	_EDC_BOOTING_CLEAR_AP_DUMP_,		/* 清空AP下載暫存資料，因更新完會直接重開機所以有暫存檔案 */
	_EDC_BOOTING_PRINT_IMAGE_INITIAL_,	/* 抓圖片高度，要放更新之後 */
	_EDC_BOOTING_LOAD_TABLE_,		/* load Table, ex: CFGT、EDC */
	_EDC_BOOTING_PROCESS_CRADLE_,		/* 若有底座連底座 */
	_EDC_BOOTING_COMM_INITIAL_,		/* 通訊初始化 */
	_EDC_BOOTING_WAIT_FOR_SWITCH_,		/* 檢測是否可連上TMS */
	_EDC_BOOTING_UPDATE_SUCCESS_REPORT_,	/* 檢查是否要回傳生效回報 */
	_EDC_BOOTING_TMSOK_CHECK_INITIAL_,	/* 確認是否有下TMS */
	_EDC_BOOTING_TMS_INQUIRE_,		/* TMS開機詢問 */
	_EDC_BOOTING_TMS_DOWNLOAD_,		/* TMS開機下載 */
	_EDC_BOOTING_TMS_DCC_SCHEDULE_,		/* TMS連動DCC下載，若有TMS有開DCC，會自動下載 */
	_FUNCTION_TMS_REBOOT_,			/* TMS下載完需要重開機更新，會在這裡 */
	_EDC_BOOTING_ECR_INITIAL_,		/* ECR初始化 */
	_EDC_BOOTING_EMV_INITIAL_,		/* EMV初始化 */
	_EDC_BOOTING_TSAM_INITIAL_,		/* 註冊及PowerOn tSAM */
	_EDC_BOOTING_FIX_INV_PROBLEM_AT_REBOOT_,/* 調閱編號補償機制 */
	_EDC_BOOTING_REPRINT_POWEROFF_,		/* 印出斷電的簽單 */
        _EDC_BOOTING_CHECK_AND_RECOVER_SETTLEMENT_XML_, /* 補結帳流程 */
	_EDC_BOOTING_CUP_LOGON_,		/* 安全認證 CUP LOGON */
	_EDC_BOOTING_ETICKET_INITIAL_,		/* 初始化票證 */
	_EDC_BOOTING_CTLS_INITIAL_,		/* 初始化感應，感應初始化要放票證後面，不然會被覆蓋設定(這個指虹堡整合的API) */
	_EDC_BOOTING_CHECK_TMS_,		/* 提示TMS是否下載參數錯誤 */
	_EDC_BOOTING_POWER_ON_PASSWORD_,	/* 輸入開機密碼 */
	_FLOW_NULL_,
};

int EDC_LOAD_KEY_BOOTING_TABLE[] =
{
	_EDC_BOOTING_DISPLAY_INITIAL_,		/* 顯示函式庫初始化 */
	_EDC_BOOTING_PRINT_INITIAL_,		/* 列印函式庫初始化 */
	_EDC_BOOTING_CASTLE_LIBRARY_INITIAL_,	/* 虹堡函式庫初始化 */
	_EDC_BOOTING_LOAD_TABLE_,		/* load Table, ex: CFGT、EDC */
	_EDC_BOOTING_SYNC_DEBUG_,		/* 同步Debug Flag */
	_EDC_BOOTING_COMM_INITIAL_,		/* 通訊初始化 */
	_EDC_BOOTING_SQLITE_INITIAL_,		/* SQLite初始化 */
	_EDC_BOOTING_LOAD_TMK_ECR_INITIAL_,	/* ECR初始化 */
	_FLOW_NULL_,
};

/* BOOTING 開機流程 */
int EDC_V3UL_BOOTING_TABLE[] =
{	
	_EDC_BOOTING_DISPLAY_INITIAL_,		/* 顯示函式庫初始化 */
	_EDC_BOOTING_CASTLE_LIBRARY_INITIAL_,	/* 虹堡函式庫初始化 */
	_EDC_BOOTING_LOAD_TABLE_,		/* load Table, ex: CFGT、EDC */
	_EDC_BOOTING_SYNC_DEBUG_,		/* 同步Debug Flag */
	_EDC_BOOTING_COMM_INITIAL_,		/* 通訊初始化 */
	_EDC_BOOTING_SQLITE_INITIAL_,		/* SQLite初始化 */
	_EDC_BOOTING_POWER_ON_PASSWORD_,	/* 輸入開機密碼 */
	_EDC_BOOTING_TMSOK_CHECK_INITIAL_,	/* 確認是否有下TMS */
	_EDC_BOOTING_ECR_INITIAL_,		/* ECR初始化 */
	_EDC_BOOTING_EMV_INITIAL_,		/* EMV初始化 */
	_EDC_BOOTING_TSAM_INITIAL_,		/* 註冊及PowerOn tSAM */
	_EDC_BOOTING_CTLS_INITIAL_,		/* 初始化感應，感應初始化要放票證後面，不然會被覆蓋設定 */
	_FLOW_NULL_,
};

/* BOOTING 開機流程 */
int EDC_SDK_INITIAL_BOOTING_TABLE[] =
{	
	_EDC_BOOTING_CASTLE_LIBRARY_INITIAL_,	/* 虹堡函式庫初始化 */
	_EDC_BOOTING_SYNC_DEBUG_,		/* 同步Debug Flag */
	_EDC_BOOTING_UPDATE_PARAMETER_POWER_ON_,/* 檢查是否需更新 */
	_EDC_BOOTING_CLEAR_AP_DUMP_,		/* 清空AP下載暫存資料，因更新完會直接重開機所以有暫存檔案 */
	_EDC_BOOTING_LOAD_TABLE_,		/* load Table, ex: CFGT、EDC */
	_SDK_COMMINITIAL_,			/* 通訊初始化，誠憶那邊會做 */
	_EDC_BOOTING_UPDATE_SUCCESS_REPORT_,	/* 檢查是否要回傳生效回報 */
	_EDC_BOOTING_TMSOK_CHECK_INITIAL_,	/* 確認是否有下TMS */
	_EDC_BOOTING_TMS_INQUIRE_,		/* TMS開機詢問 */
	_EDC_BOOTING_TMS_DOWNLOAD_,		/* TMS開機下載 */
//	_EDC_BOOTING_TMS_DCC_SCHEDULE_,		/* TMS連動DCC下載，若有TMS有開DCC，會自動下載 */
	_FUNCTION_TMS_REBOOT_,			/* TMS下載完需要重開機更新，會在這裡 */
//	_EDC_BOOTING_PROCESS_CRADLE_,		/* 若有底座連底座的藍芽 */
	_EDC_BOOTING_SQLITE_INITIAL_,		/* SQLite初始化 */
	_EDC_BOOTING_EMV_INITIAL_,		/* EMV初始化 */
	_EDC_BOOTING_TSAM_INITIAL_,		/* 註冊及PowerOn tSAM */
//	_EDC_BOOTING_REPRINT_POWEROFF_,		/* 印出斷電的簽單 */
//	_EDC_BOOTING_ETICKET_INITIAL_,		/* 初始化票證 */
	_EDC_BOOTING_CTLS_INITIAL_,		/* 初始化感應，感應初始化要放票證後面，不然會被覆蓋設定(這個指虹堡整合的API) */
	_EDC_BOOTING_CUP_LOGON_,		/* 安全認證 CUP LOGON */
	_EDC_BOOTING_POWER_ON_PASSWORD_,	/* 輸入開機密碼 */
	_FLOW_NULL_,
};

/* REBOOT 重新開機 */
int EDC_REBOOT_TABLE[] =
{
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,	/* 立即回傳 */
        _NCCC_FUNCTION_SEND_ECR_AFTER_PRINT_RECEIPT_,
	_FUNCTION_REBOOT_,
	_FLOW_NULL_,
};

/* 省電睡眠流程 */
int POWER_SAVING_SLEEP_TABLE[] =
{
	_POWER_SAVING_FLOW_SLEEP_,
	_FLOW_NULL_,
};
	
/* 省電流程 */
int POWER_SAVING_STANDBY_TABLE[] =
{
	_POWER_SAVING_FLOW_STANDBY_,
	_FLOW_NULL_,
};

/* 票證消費扣款 */
int TICKET_DEDUCT_TABLE[] =
{	
	_FUNCTION_CHECK_TERM_STATUS_,
	_FUNCTION_CHECK_TERM_STATUS_TICKET_,
	_TICKET_DISPLAY_LOGON_RESULT_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_TICKET_GET_ESVC_CARD_FLOW_,
	_TICKET_DECIDE_TRANS_TYPE_,
	_FLOW_NULL_,
};

/* 票證查詢餘額 */
int TICKET_CHECK_BALANCE_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_FUNCTION_CHECK_TERM_STATUS_TICKET_,
	_TICKET_DISPLAY_LOGON_RESULT_,
	_TICKET_GET_ESVC_CARD_FLOW_,
	_TICKET_DECIDE_TRANS_TYPE_,
	_FLOW_NULL_,
};

/* 票證加值餘額 */
int TICKET_TOPUP_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_FUNCTION_CHECK_TERM_STATUS_TICKET_,
	_TICKET_DISPLAY_LOGON_RESULT_,
	_CREDIT_FUNCTION_GET_AMOUNT_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_TICKET_GET_ESVC_CARD_FLOW_,
	_TICKET_DECIDE_TRANS_TYPE_,
	_FLOW_NULL_,
};

/* 票證退貨 */
int TICKET_REFUND_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_FUNCTION_CHECK_TERM_STATUS_TICKET_,
	_TICKET_DISPLAY_LOGON_RESULT_,
	_CREDIT_FUNCTION_GET_OPT_ORI_TRANSDATE_ESVC_,
	_CREDIT_FUNCTION_GET_OPT_REFUND_AMOUNT_,
	_CREDIT_FUNCTION_GET_RF_NUMBER_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_TICKET_GET_ESVC_CARD_FLOW_,
	_TICKET_DECIDE_TRANS_TYPE_,
	_FLOW_NULL_,
};

/* 票證加值取消 */
int TICKET_VOID_TOP_UP_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_FUNCTION_CHECK_TERM_STATUS_TICKET_,
	_TICKET_DISPLAY_LOGON_RESULT_,
	_CREDIT_FUNCTION_GET_OPT_STOREID_,
	_CREDIT_FUNCTION_GET_OPT_PRODUCT_CODE_,
	_TICKET_GET_ESVC_CARD_FLOW_,
	_TICKET_DECIDE_TRANS_TYPE_,
	_TICKET_GET_VOID_TOP_UP_AMOUNT_FROM_BATCH_,
	_FLOW_NULL_,
};

/* 票證 SAM 註冊 */
int TICKET_SAM_REGISTER_OPERATION_TABLE[] =
{
	_TICKET_FUNC_IPASS_REGISTER_,
	_FLOW_NULL_,
};

/* 票證Retry流程 */
int TICKET_RETRY_OPERATION_TABLE[] = 
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_FUNCTION_CHECK_TERM_STATUS_TICKET_,
	_TICKET_GET_CARD_ECC_RETRY_FLOW,
	_TICKET_DECIDE_TRANS_TYPE_,
	_TICKET_GET_VOID_TOP_UP_AMOUNT_FROM_BATCH_,
	_FLOW_NULL_,
};

/* 票證AutoSignOn流程 */
int TICKET_AUTO_SIGNON_OPERATION_TABLE[] = 
{
	_TICKET_AUTO_SIGN_ON_FLOW,
	_FLOW_NULL_,
};

int LOAD_KEY_FROM_MASTER[] = 
{
	_FUNCTION_ECR_LOAD_TMK_,
	_NCCC_TMK_SELECT_DEVICE_,
	_FLOW_NULL_,
};

int LOAD_KEY_FROM_KEY_CARD_TABLE[] = 
{
	_NCCC_TMK_SELECT_AID_,
	_NCCC_TMK_GET_APPLET_INFO_,
	_NCCC_TMK_GET_KEY_INFO_MULTI_KEY_,
	_NCCC_TMK_GENERATE_RANDOM_NUMBER_,
	_NCCC_TMK_VERIFY_OTP_,
	_NCCC_TMK_GET_TMK_MULTI_,
	_NCCC_TMK_SELECT_DEVICE_,
	_FLOW_NULL_,
};

int REPRINT_CUS_075_MENU_TABLE[] = 
{
	_NCCC_FUNCTION_CUS_075_MENU_WHEN_ECR_,
	_FLOW_NULL_,
};

int REPRINT_CUS_075_OPERATION_TABLE[] = 
{
	_FUNCTION_GET_HOST_NUM_FLOW_,
	_FUNCTION_USER_CHOICE_,
	_FUNCTION_ECR_SEND_TRANSACTION_RESULT_,
        _NCCC_FUNCTION_SEND_ECR_AFTER_PRINT_RECEIPT_,
	_FUNCTION_REPRINT_RECEIPT_BY_BUFFER_,
	_FLOW_NULL_,
};

int TRUST_SALE_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_FUNCTION_IDLE_CHECKCUSTOMPASSWORD_FLOW_,
	_NCCC_TRUST_DEAL_TRUST_TXN_PARAMETER_OPT_,
        _CREDIT_FUNCTION_GET_OPT_TRUST_BENEFICIARYID_,
        _CREDIT_FUNCTION_GET_OPT_PATIENTID_,
	_CREDIT_FUNCTION_GET_OPT_TRUST_VERIFICATIONCODE_,
        _CREDIT_FUNCTION_GET_OPT_TRUSTINSTITUTIONCODE_,
        _CREDIT_FUNCTION_GET_OPT_RECONCILIATIONNO_,
	_CREDIT_FUNCTION_GET_OPT_AMOUNT_TRUST_,
	_FLOW_NULL_ ,
};

int TRUST_VOID_OPERATION_TABLE[] =
{
	_FUNCTION_CHECK_TERM_STATUS_,
	_FUNCTION_IDLE_CHECKCUSTOMPASSWORD_FLOW_,
	_NCCC_TRUST_DEAL_TRUST_TXN_PARAMETER_OPT_,
        _CREDIT_FUNCTION_GET_OPT_ORI_TRANSDATE_TRUST_,        /* 原交易日期 */
        _CREDIT_FUNCTION_GET_OPT_TRUSTINSTITUTIONCODE_,
        _CREDIT_FUNCTION_GET_OPT_TRUST_RRN_,
	_CREDIT_FUNCTION_GET_OPT_AMOUNT_TRUST_,
	_NCCC_TRUST_VOID_CONFIRM_,
	_FLOW_NULL_ ,
};

OPT_TABLE OPERATION_TABLE[] =
{
	{_OPERATION_MULTIFUNC_SLAVE_,			MULTIFUNC_SLAVE_TRANSACTION_TABLE},
	{_OPERATION_SALE_,				SALE_OPERATION_TABLE},
	{_OPERATION_SALE_ICC_,				SALE_ICC_OPERATION_TABLE},
	{_OPERATION_SALE_CTLS_,				SALE_CTLS_OPERATION_TABLE},
	{_OPERATION_SALE_CTLS_IDLE_,			SALE_CTLS_IDLE_OPERATION_TABLE},
	{_OPERATION_SALE_BARCODE_,			SALE_BARCODE_OPERATION_TABLE},		/* (需求單-109455)-Üny實體掃碼需求 by Russell 2021/9/10 上午 10:32 */
	{_OPERATION_FISC_SALE_,				FISC_SALE_OPERATION_TABLE},
	{_OPERATION_FISC_SALE_CTLS_,			FISC_SALE_CTLS_OPERATION_TABLE},
	{_OPERATION_INST_SALE_CTLS_,			INST_SALE_CTLS_OPERATION_TABLE},
	{_OPERATION_INST_SALE_BARCODE_,			INST_SALE_BARCODE_OPERATION_TABLE},	/* (需求單-109455)-Üny實體掃碼需求 by Russell 2021/9/10 上午 10:32 */
	{_OPERATION_INST_REFUND_CTLS_,			INST_REFUND_CTLS_OPERATION_TABLE},
	{_OPERATION_INST_REFUND_BARCODE_,		INST_REFUND_BARCODE_OPERATION_TABLE},	/* (需求單-109455)-Üny實體掃碼需求 by Russell 2021/9/10 上午 10:32 */
	{_OPERATION_INST_ADJUST_,			INST_ADJUST_OPERATION_TABLE},
	{_OPERATION_INST_ADJUST_CTLS_,			INST_ADJUST_CTLS_OPERATION_TABLE},
	{_OPERATION_REDEEM_SALE_CTLS_,			REDEEM_SALE_CTLS_OPERATION_TABLE},
	{_OPERATION_REDEEM_SALE_BARCODE_,		REDEEM_SALE_BARCODE_OPERATION_TABLE},	/* (需求單-109455)-Üny實體掃碼需求 by Russell 2021/9/10 上午 10:32 */
	{_OPERATION_REDEEM_REFUND_CTLS_,		REDEEM_REFUND_CTLS_OPERATION_TABLE},
	{_OPERATION_REDEEM_REFUND_BARCODE_,		REDEEM_REFUND_BARCODE_OPERATION_TABLE},	/* (需求單-109455)-Üny實體掃碼需求 by Russell 2021/9/10 上午 10:32 */
	{_OPERATION_REDEEM_ADJUST_,			REDEEM_ADJUST_OPERATION_TABLE},
	{_OPERATION_REDEEM_ADJUST_CTLS_,		REDEEM_ADJUST_CTLS_OPERATION_TABLE},
	{_OPERATION_VOID_,				VOID_OPERATION_TABLE},
	{_OPERATION_REFUND_,				REFUND_OPERATION_TABLE},
	{_OPERATION_REFUND_AMOUNT_FIRST_,		REFUND_AMOUNT_FIRST_OPERATION_TABLE},
	{_OPERATION_REFUND_CTLS_,			REFUND_CTLS_OPERATION_TABLE},
	{_OPERATION_REFUND_AMOUNT_FIRST_CUP_,		REFUND_AMOUNT_FIRST_CUP_OPERATION_TABLE},
	{_OPERATION_REFUND_CTLS_CUP_,			REFUND_CTLS_CUP_OPERATION_TABLE},
        {_OPERATION_REFUND_CTLS_GET_CARD_FIRST_,	REFUND_CTLS_GET_CARD_FIRST_OPERATION_TABLE},
	{_OPERATION_REFUND_BARCODE_,			REFUND_BARCODE_OPERATION_TABLE},
	{_OPERATION_FISC_REFUND_,			FISC_REFUND_OPERATION_TABLE},
	{_OPERATION_FISC_REFUND_CTLS_,			FISC_REFUND_CTLS_OPERATION_TABLE},
	{_OPERATION_SETTLE_,				SETTLE_OPERATION_TABLE},
	{_OPERATION_TIP_,				TIP_OPERATION_TABLE},
	{_OPERATION_SALE_OFFLINE_,			SALE_OFFLINE_OPERATION_TABLE},
	{_OPERATION_SALE_OFFLINE_CTLS_,			SALE_OFFLINE_CTLS_OPERATION_TABLE},
	{_OPERATION_ADJUST_,				ADJUST_OPERATION_TABLE},
	{_OPERATION_PRE_AUTH_,				PRE_AUTH_OPERATION_TABLE},
	{_OPERATION_PRE_AUTH_CTLS_,			PRE_AUTH_CTLS_OPERATION_TABLE},
	{_OPERATION_PRE_COMP_,				PRE_COMP_OPERATION_TABLE},
	{_OPERATION_PRE_COMP_CTLS_,			PRE_COMP_CTLS_OPERATION_TABLE},
	{_OPERATION_MAIL_ORDER_,			MAIL_ORDER_OPERATION_TABLE},
	{_OPERATION_LOYALTY_REDEEM_,			LOYALTY_REDEEM_OPERATION_TABLE},
	{_OPERATION_LOYALTY_REDEEM_CTLS_,		LOYALTY_REDEEM_CTLS_OPERATION_TABLE},
	{_OPERATION_BARCODE_,				BARCODE_OPERATION_TABLE},
	{_OPERATION_VOID_LOYALTY_REDEEM_,		VOID_LOYALTY_REDEEM_OPERATION_TABLE},
	{_OPERATION_TOTAL_REPORT_,			PRINT_TOTAL_OPERATION_BY_BUFFER_TABLE},
	{_OPERATION_DETAIL_REPORT_,			PRINT_DETAIL_OPERATION_BY_BUFFER_TABLE},
	{_OPERATION_DELETE_BATCH_,			DELETE_BATCH_OPERATION_TABLE},
	{_OPERATION_REVIEW_,				REVIEW_OPRATION_TABLE},
	{_OPERATION_REVIEW_TOTAL_,			REVIEW_TOTAL_OPRATION_TABLE},
	{_OPERATION_REVIEW_DETAIL_,			REVIEW_DETAIL_OPRATION_TABLE},
	{_OPERATION_REPRINT_,				REPRINT_OPERATION_TABLE},
	{_OPERATION_TSAM_,				TSAM_OPERATION_TABLE},
	{_OPERATION_FUN7_PRINT_,			PRINT_PARAM_TERM_BYBUFFER_TABLE},
	{_OPERATION_FUN7_DCC_PRINT_,			PRINT_DCC_PARAM_TERM_BYBUFFER_TABLE},
	{_OPERATION_FUN4_PRINT_,			SIGNPAD_TEST_TABLE},
	{_OPERATION_FUN5_TMS_DOWNLOAD_,			FUN5_TMS_DOWNLOAD_TABLE},
	{_OPERATION_FUN5_TMS_TASK_REPORT_,		FUN5_RETURN_TASK_REPORT_TABLE},
	{_OPERATION_FUN5_DCC_DOWNLOAD_,			FUN5_DCC_DOWNLOAD_TABLE},
	{_OPERATION_FUN6_TMS_DOWNLOAD_,			FUN6_TMS_DOWNLOAD_TABLE},
	{_OPERATION_FUN6_TMS_TRACELOG_UP_,		FUN6_TMS_TRACELOG_UPLOAD_TABLE},
	{_OPERATION_FUNC_TMS_TRACELOG_PRINT_,		FUNC_TMS_TRACELOG_PRINT_TABLE},
	{_OPERATION_FUN6_DCC_DOWNLOAD_,			FUN6_DCC_DOWNLOAD_TABLE},
	{_OPERATION_FUN6_DCC_RATE_DOWNLOAD_,		FUN6_DCC_RATE_DOWNLOAD_TABLE},
	{_OPERATION_FUN1_READERINIT_,			FUN1_READERINIT_TABLE},
	{_OPERATION_ECR_TRANSACTION_,			ECR_TRANSACTION_TABLE},
	{_OPERATION_ESC_IDLE_UPLOAD_,			ESC_UPLOAD_IDLE_TABLE},
	{_OPERATION_DCC_SCHEDULE_,			DCC_SCHEDULE_TABLE},
	{_OPERATION_TMS_DCC_SCHEDULE_,			TMS_DCC_SCHEDULE},
	{_OPERATION_DCC_HOUR_NOTIFY_,			DCC_HOUR_NOTIFY},
	{_OPERATION_TMS_SCHEDULE_INQUIRE_,		TMS_SCHEDULE_INQUIRE_TABLE},
	{_OPERATION_TMS_SCHEDULE_DOWNLOAD_,		TMS_SCHEDULE_DOWNLOAD_TABLE},
	{_OPERATION_TMS_PROCESS_EFFECTIVE_,		TMS_PROCESS_EFFECTIVE_TABLE},
	{_OPERATION_HG_,				HG_OPERATION_TABLE},
	{_OPERATION_HG_REFUND_,				HG_REFUND_OPERATION_TABLE},
	{_OPERATION_HG_I_R_,				HG_I_R_OPERATION_TABLE},
	{_OPERATION_HG_INST_SALE_CTLS_,			HG_INST_SALE_CTLS_OPERATION_TABLE},
	{_OPERATION_HG_REDEEM_SALE_CTLS_,		HG_REDEEM_SALE_CTLS_OPERATION_TABLE},
	{_OPERATION_EDC_BOOTING_,			EDC_BOOTING_TABLE},
	{_OPERATION_EDC_LOAD_KEY_BOOTING_,		EDC_LOAD_KEY_BOOTING_TABLE},
	{_OPERATION_EDC_V3UL_BOOTING_,			EDC_V3UL_BOOTING_TABLE},
	{_OPERATION_EDC_SDK_INITIAL_BOOTING_,		EDC_SDK_INITIAL_BOOTING_TABLE},
	{_OPERATION_EDC_REBOOT_,			EDC_REBOOT_TABLE},
	{_OPERATION_POWER_SAVING_SLEEP_,		POWER_SAVING_SLEEP_TABLE},
	{_OPERATION_POWER_SAVING_STANDBY_,		POWER_SAVING_STANDBY_TABLE},
	{_OPERATION_TICKET_DEDUCT_,			TICKET_DEDUCT_TABLE},
	{_OPERATION_TICKET_INQUIRY_,			TICKET_CHECK_BALANCE_TABLE},
	{_OPERATION_TICKET_TOP_UP_,			TICKET_TOPUP_TABLE},
	{_OPERATION_TICKET_REFUND_,			TICKET_REFUND_TABLE},
	{_OPERATION_TICKET_VOID_TOP_UP_,		TICKET_VOID_TOP_UP_TABLE},
	{_OPERATION_TICKET_SAM_REGISTER_,		TICKET_SAM_REGISTER_OPERATION_TABLE},
	{_OPERATION_TICKET_RETRY_,			TICKET_RETRY_OPERATION_TABLE},
	{_OPERATION_ESVC_AUTO_SIGNON_,			TICKET_AUTO_SIGNON_OPERATION_TABLE},
	{_OPERATION_LOAD_KEY_FROM_MASTER_,		LOAD_KEY_FROM_MASTER},
	{_OPERATION_LOAD_KEY_FROM_KEY_CARD_,		LOAD_KEY_FROM_KEY_CARD_TABLE},
	{_OPERATION_REPRINT_CUS_075_MENU_,		REPRINT_CUS_075_MENU_TABLE},
	{_OPERATION_REPRINT_NORMAL_,			REPRINT_NORMAL_OPERATION_TABLE},
	{_OPERATION_REPRINT_CUS_075_,			REPRINT_CUS_075_OPERATION_TABLE},
	{_OPERATION_ECR_TRANSACTION_NORMAL_,		ECR_TRANSACTION_NORMAL_TABLE},
	{_OPERATION_IPASS_READER_,			IPASS_READER_TABLE},
	{_OPERATION_TRUST_SALE_,			TRUST_SALE_OPERATION_TABLE},
        {_OPERATION_TRUST_VOID_,			TRUST_VOID_OPERATION_TABLE},
	{_FLOW_NULL_ ,					NULL}
	/*inOPTCode					*inOPTID*/
};

int inFLOW_RunFunction(TRANSACTION_OBJECT *pobTran, int inFuncID)
{
        int     i, inRetVal;

        for (i = 0 ;; i ++)
        {
                if (FunctionTable[i].inFuncId == 0)
                {
                        return (VS_ERROR);
                }
                else if (FunctionTable[i].inFuncId == inFuncID)
                {
                        inRetVal = FunctionTable[i].inFunctionPoint(pobTran);
                        break;
                }
        }

        return (inRetVal);
}

int inFLOW_RunOperation(TRANSACTION_OBJECT *pobTran, int inOPTCode)
{
        int     *inOPTID = NULL;
        int     i, inRetVal = VS_ERROR ;

        /* 決定要跑哪個operation table */
        for (i = 0 ;; i ++)
        {
                if (OPERATION_TABLE[i].inOPTCode == inOPTCode)
                {
                        inOPTID = OPERATION_TABLE[i].inOPTID;
                        break;
                }
                else if (OPERATION_TABLE[i].inOPTCode == -1)
                        break;
        }

        if (inOPTID == NULL)
        {
                return (VS_ERROR);
        }

        for (i = 0 ; ; i ++)
        {
                if (inOPTID[i] == _FLOW_NULL_)
                        break;

                inRetVal = inFLOW_RunFunction(pobTran, inOPTID[i]);

		if (inRetVal == VS_LAST_PAGE)
		{
			/* 選擇回上一頁 */
			i -= 2;
		}
                else if (inRetVal == VS_SUCCESS)
                {
                        /* 成功，繼續下一步 */
                }
		else
		{
			/* 票證流程失敗，要切回NCCC AID */
			if (inOPTCode == _OPERATION_TICKET_DEDUCT_	||
			    inOPTCode == _OPERATION_TICKET_INQUIRY_	||
			    inOPTCode == _OPERATION_TICKET_TOP_UP_	||
			    inOPTCode == _OPERATION_TICKET_REFUND_	||
			    inOPTCode == _OPERATION_TICKET_VOID_TOP_UP_	||
			    inOPTCode == _OPERATION_TICKET_RETRY_	||
			    inOPTCode == _OPERATION_ESVC_AUTO_SIGNON_)
			{
				/* 切回NCCC */
				inNCCC_tSAM_SelectAID_NCCC_Flow();
			}
			
			break;
		}
        }

        return (inRetVal);
}
