/* 
 * File:   APDU_Define.h
 * Author: RussellBai
 *
 * Created on 2022年9月29日, 下午 8:20
 */

#ifndef APDU_DEFINE_H
#define	APDU_DEFINE_H

#ifdef	__cplusplus
extern "C" {
#endif




#ifdef	__cplusplus
}
#endif

#endif	/* APDU_DEFINE_H */

#define _EMV_SELECT_AID_CLA_COMMAND_			0x00
#define _EMV_SELECT_AID_INS_COMMAND_			0xA4
#define _EMV_SELECT_AID_P1_COMMAND_			0x04
#define _EMV_SELECT_AID_P2_COMMAND_			0x00
#define _EMV_SELECT_AID_LC_SIZE_			8
#define _EMV_SELECT_AID_LE_COMMAND_			0x00

#define _FISC_SELECT_AID_CLA_COMMAND_                   0x00
#define _FISC_SELECT_AID_INS_COMMAND_                   0xA4
#define _FISC_SELECT_AID_P1_COMMAND_                    0x04
#define _FISC_SELECT_AID_P2_COMMAND_                    0x00
#define _FISC_SELECT_AID_LC_SIZE_                       8
#define _FISC_SELECT_AID_LE_COMMAND_                    0x00

#define _TICKET_SELECT_AID_CLA_COMMAND_                 0x00
#define _TICKET_SELECT_AID_INS_COMMAND_                 0xA4
#define _TICKET_SELECT_AID_P1_COMMAND_                  0x04
#define _TICKET_SELECT_AID_P2_COMMAND_                  0x00
#define _TICKET_SELECT_AID_LC_SIZE_                     8
#define _TICKET_SELECT_AID_LE_COMMAND_                  0x00

#define _FISC_VERIFY_PIN_CLA_COMMAND_                   0x00
#define _FISC_VERIFY_PIN_INS_COMMAND_                   0x20
#define _FISC_VERIFY_PIN_P1_COMMAND_                    0x00
#define _FISC_VERIFY_PIN_P2_COMMAND_                    0x10
#define _FISC_VERIFY_PIN_LC_SIZE_                       8

#define _FISC_SELECT_EF_CLA_COMMAND_                    0x00
#define _FISC_SELECT_EF_INS_COMMAND_                    0xA4
#define _FISC_SELECT_EF_P1_COMMAND_                     0x02
#define _FISC_SELECT_EF_P2_COMMAND_                     0x00
#define _FISC_SELECT_EF_LC_SIZE_                        2

#define _FISC_READ_RECORDS_CLA_COMMAND_                 0x00
#define _FISC_READ_RECORDS_INS_COMMAND_                 0xB2
#define _FISC_READ_RECORDS_P1_COMMAND_                  0x01
#define _FISC_READ_RECORDS_P2_COMMAND_                  0x05
#define _FISC_READ_RECORDS_LE_COMMAND_                  0x00
#define _FISC_READ_RECORDS_LC_SIZE_			0

#define _FISC_WRITE_RECORD_CLA_COMMAND_                 0x00
#define _FISC_WRITE_RECORD_INS_COMMAND_                 0xE2
#define _FISC_WRITE_RECORD_P1_COMMAND_                  0x10
#define _FISC_WRITE_RECORD_P2_COMMAND_                  0x80
#define _FISC_WRITE_RECORD_P2_COMMAND_CTLS_		0x90
#define _FISC_WRITE_RECORD_LE_COMMAND_			0x00

#define _FISC_WRITE_AUTH_RECORD_CLA_COMMAND_		0x00
#define _FISC_WRITE_AUTH_RECORD_INS_COMMAND_		0xD4
#define _FISC_WRITE_AUTH_RECORD_P1_COMMAND_		0x00
#define _FISC_WRITE_AUTH_RECORD_P2_COMMAND_		0x00
#define _FISC_WRITE_AUTH_RECORD_LE_COMMAND_		0x00

#define _FISC_READ_AUTH_RECORD_CLA_COMMAND_		0x00
#define _FISC_READ_AUTH_RECORD_INS_COMMAND_		0xB4
#define _FISC_READ_AUTH_RECORD_P1_COMMAND_		0x01
#define _FISC_READ_AUTH_RECORD_P2_COMMAND_		0x00
#define _FISC_READ_AUTH_RECORD_LE_COMMAND_		0x00

#define _NCCC_TMK_KEY_CARD_SELECT_AID_CLA_COMMAND_	0x00
#define _NCCC_TMK_KEY_CARD_SELECT_AID_INS_COMMAND_	0xA4
#define _NCCC_TMK_KEY_CARD_SELECT_AID_P1_COMMAND_	0x04
#define _NCCC_TMK_KEY_CARD_SELECT_AID_P2_COMMAND_	0x00
#define _NCCC_TMK_KEY_CARD_SELECT_AID_LE_COMMAND_	0x00
#define _NCCC_TMK_KEY_CARD_SELECT_AID_LC_SIZE_		8

#define _NCCC_TMK_KEY_CARD_GET_APPLET_INFO_CLA_COMMAND_	0x80
#define _NCCC_TMK_KEY_CARD_GET_APPLET_INFO_INS_COMMAND_	0x12
#define _NCCC_TMK_KEY_CARD_GET_APPLET_INFO_P1_COMMAND_	0x00
#define _NCCC_TMK_KEY_CARD_GET_APPLET_INFO_P2_COMMAND_	0x00
#define _NCCC_TMK_KEY_CARD_GET_APPLET_INFO_LE_COMMAND_	0x00
#define _NCCC_TMK_KEY_CARD_GET_APPLET_INFO_LC_SIZE_	0

#define _NCCC_TMK_KEY_CARD_GET_KEY_INFO_CLA_COMMAND_		0x80
#define _NCCC_TMK_KEY_CARD_GET_KEY_INFO_INS_COMMAND_		0xC0
#define _NCCC_TMK_KEY_CARD_GET_KEY_INFO_P1_COMMAND_		0x00
#define _NCCC_TMK_KEY_CARD_GET_KEY_INFO_SINGLE_KEY_P2_COMMAND_	0x00
#define _NCCC_TMK_KEY_CARD_GET_KEY_INFO_MULTI_KEY_P2_COMMAND_	0x01
#define _NCCC_TMK_KEY_CARD_GET_KEY_INFO_LE_COMMAND_		0x00
#define _NCCC_TMK_KEY_CARD_GET_KEY_INFO_LC_SIZE_		0

#define _NCCC_TMK_KEY_CARD_GEN_RANDOM_NUM_CLA_COMMAND_	0x80
#define _NCCC_TMK_KEY_CARD_GEN_RANDOM_NUM_INS_COMMAND_	0x86
#define _NCCC_TMK_KEY_CARD_GEN_RANDOM_NUM_P1_COMMAND_	0x00
#define _NCCC_TMK_KEY_CARD_GEN_RANDOM_NUM_P2_COMMAND_	0x00
#define _NCCC_TMK_KEY_CARD_GEN_RANDOM_NUM_LE_COMMAND_	0x08
#define _NCCC_TMK_KEY_CARD_GEN_RANDOM_NUM_LC_SIZE_	0

#define _NCCC_TMK_KEY_CARD_VERIFY_OTP_CLA_COMMAND_	0x80
#define _NCCC_TMK_KEY_CARD_VERIFY_OTP_INS_COMMAND_	0x20
#define _NCCC_TMK_KEY_CARD_VERIFY_OTP_P1_COMMAND_	0x00
#define _NCCC_TMK_KEY_CARD_VERIFY_OTP_P2_COMMAND_	0x00
#define _NCCC_TMK_KEY_CARD_VERIFY_OTP_LC_SIZE_		8

#define _NCCC_TMK_KEY_CARD_GET_TMK_CLA_COMMAND_			0x80
#define _NCCC_TMK_KEY_CARD_GET_TMK_INS_COMMAND_			0xC2
#define _NCCC_TMK_KEY_CARD_GET_TMK_P1_COMMAND_			0x00
#define _NCCC_TMK_KEY_CARD_GET_TMK_SINGLE_KEY_P2_COMMAND_	0x00
#define _NCCC_TMK_KEY_CARD_GET_TMK_MULTI_KEY_P2_COMMAND_	0x01
#define _NCCC_TMK_KEY_CARD_GET_TMK_LE_COMMAND_			0x00
#define _NCCC_TMK_KEY_CARD_GET_TMK_LE2_COMMAND_			0x00
#define _NCCC_TMK_KEY_CARD_GET_TMK_LE3_COMMAND_			0x00

#define ICC_FPG_FTC_EFID_01		"\xFE\x01"
#define ICC_FPG_FTC_EFID_02		"\xFE\x02"

#define FPG_FTC_EFID_C0			"\xFE\xC0"
#define FPG_FTC_EFID_SVC1		"\xFE\x90"
#define FPG_FTC_EFID_SVC2		"\xFE\x91"
#define FPG_FTC_EFID_SVC3		"\xFE\x92"
#define FPG_FTC_EFID_SVC4		"\xFE\x93"
#define FPG_FTC_EFID_SVC5		"\xFE\x94"

#define ICC_FPG_FTC_SELECT_AID_CLA		(BYTE)0x00
#define ICC_FPG_FTC_SELECT_AID_INS		(BYTE)0xA4
#define ICC_FPG_FTC_SELECT_AID_P1		(BYTE)0x04
#define ICC_FPG_FTC_SELECT_AID_P2		(BYTE)0x00
#define ICC_FPG_FTC_SELECT_AID_LC		(BYTE)0x0C

#define ICC_FPG_FTC_SELECT_EF_CLA		(BYTE)0x00
#define ICC_FPG_FTC_SELECT_EF_INS		(BYTE)0xA4
#define ICC_FPG_FTC_SELECT_EF_P1		(BYTE)0x02
#define ICC_FPG_FTC_SELECT_EF_P2		(BYTE)0x00
#define ICC_FPG_FTC_SELECT_EF_LC		(BYTE)0x02

#define ICC_FPG_FTC_SELECT_MF_CLA		(BYTE)0x00
#define ICC_FPG_FTC_SELECT_MF_INS		(BYTE)0xA4
#define ICC_FPG_FTC_SELECT_MF_P1		(BYTE)0x03
#define ICC_FPG_FTC_SELECT_MF_P2		(BYTE)0x00

#define ICC_FPG_FTC_READ_RECORD_CLA		(BYTE)0x00
#define ICC_FPG_FTC_READ_RECORD_INS		(BYTE)0xB2
#define ICC_FPG_FTC_READ_RECORD_P1		(BYTE)0x01
#define ICC_FPG_FTC_READ_RECORD_P2		(BYTE)0x04

#define ICC_FPG_FTC_READ_BINARY_CLA		(BYTE)0x00
#define ICC_FPG_FTC_READ_BINARY_INS		(BYTE)0xB0
#define ICC_FPG_FTC_READ_BINARY_P1		(BYTE)0x00
#define ICC_FPG_FTC_READ_BINARY_P2		(BYTE)0x00
#define ICC_FPG_FTC_READ_BINARY_LC		(BYTE)0x08

#define ICC_FPG_FTC_READ_BALANCE_CLA		(BYTE)0x00
#define ICC_FPG_FTC_READ_BALANCE_INS		(BYTE)0x5C
#define ICC_FPG_FTC_READ_BALANCE_P1		(BYTE)0xFE
#define ICC_FPG_FTC_READ_BALANCE_90_P2		(BYTE)0x90
#define ICC_FPG_FTC_READ_BALANCE_91_P2		(BYTE)0x91

#define _WRITE_RECORD_SIZE_                             100

#define _EMV_READ_RECORDS_CLA_COMMAND_                  0x00
#define _EMV_READ_RECORDS_INS_COMMAND_                  0xB2
#define _EMV_READ_RECORDS_01_P1_COMMAND_                0x01
#define _EMV_READ_RECORDS_P2_COMMAND_                   0x0C
#define _EMV_READ_RECORDS_LC_SIZE_			0
#define _EMV_READ_RECORDS_LE_COMMAND_                   0x00