int inHG_RunTRT(TRANSACTION_OBJECT *pobTran, int inTRTCode);
int inHG_Func_VOID_Confirm(TRANSACTION_OBJECT *pobTran);
int inHG_Func_Must_SETTLE(TRANSACTION_OBJECT *pobTran);
int inHG_Func_Check_Transaction_Function(int inHGTransactionType);
int inHG_Func_Check_Transaction_Function_Flow(TRANSACTION_OBJECT *pobTran);
int inHG_Func_Reset_PIN(TRANSACTION_OBJECT *pobTran);
int inHG_Func_GetPoint(TRANSACTION_OBJECT *pobTran);
int inHG_Func_DispTransBalancePoint(TRANSACTION_OBJECT *pobTran);
int inHG_Func_SelectPaymentRefund(TRANSACTION_OBJECT *pobTran);
int inHG_Func_SelectPaymentType(TRANSACTION_OBJECT *pobTran);
int inHG_Func_SelectTransactionTypeInstRedeem(TRANSACTION_OBJECT *pobTran);
int inHG_Func_SelectInstRedeemPaymentType(TRANSACTION_OBJECT *pobTran);
int inHG_Func_SelectVoidTRT(TRANSACTION_OBJECT *pobTran);
int inHG_Func_SelectHostTRT(TRANSACTION_OBJECT *pobTran);
int inHG_Func_ACCUM_UpdateFlow(TRANSACTION_OBJECT *pobTran);
int inHG_StoreRecord(HG_ACCUM_TOTAL_REC *srHGAccumRec, unsigned char *uszFileName);
int inHG_GetRecord(TRANSACTION_OBJECT *pobTran, HG_ACCUM_TOTAL_REC *srHGAccumRec);
int inHG_Func_VOID_RunMultiFlow(TRANSACTION_OBJECT *pobTran);
int inHG_Func_Sync_BatchNumber(TRANSACTION_OBJECT *pobTran);
int inHG_Func_Display_Complete(TRANSACTION_OBJECT *pobTran);
int inHG_Func_Online_Redeem_Credit_Flow(TRANSACTION_OBJECT *pobTran);
int inHG_Func_Customer_Check_Transaction_Function(int inHGTransactionType);
