#ifndef IPASS_MP_LIB_CONFIG
#  define IPASS_MP_LIB_CONFIG

//#  define CONFIG_QP3000S
#  define CONFIG_QP3000E
#  define DEDUCTVALUE_OFF_LINE
#  undef DEBUG_MODE
#  undef  USE_FLASH
#  define FUN_RWREGISTER
#  define CONFIG_SET_DEVICE_ID

// Enabled features (order by alphabet)
#  define CONFIG_COMPILER_HAS_WARNING   //要顯示警告字.
#  define CONFIG_DEVELOPMENT_TOOLS
#  define CONFIG_FLASH_DATA_ROUND_8
#  define CONFIG_FLASH_IO_BY_RECORD_NO
#  define CONFIG_INT_TYPES_STDLIB
#  define CONFIG_POLL_CARD_MAXIMUM_TIME 30000
#  define CONFIG_POLL_CARD_MINIMAL_TIME 300
#  define CONFIG_READ_CACHE
#  define CONFIG_READ_CARD_TIMED_RETRY_MS 2000
#  define CONFIG_RESET_BETWEEN_POLL_MS 300
#  define CONFIG_SLEEP_BETWEEN_POLL_INTERVAL_MS 10
#  define CONFIG_TIME_H_HOME_MADE
#  define CONFIG_WRITE_CARD_TIMED_RETRY_MS 2000
#  define CONFIG_QUERYTICKET_QUALIF  //小規模特店.自動加值後詢卡. // Fix_UIPara_v2000 vike.2017_09_18

#ifdef DEBUG_MODE // Fix_UIPara_v2000 vike.2017_09_18
  #define CONFIG_DEBUG_PRINT_SLEEP_INTERVAL_MS (20) //Debug輸出延遲.
#else
  #undef  CONFIG_DEBUG_PRINT_SLEEP_INTERVAL_MS //(12)//Debug輸出延遲.
#endif

// Tickless version for mifare retry.
/* #  define CONFIG_MIFARE_RETRY_COUNT 5 */
/* #  define CONFIG_POLL_CARD_MAXIMUM_TIME 2000 */
/* #  define CONFIG_POLL_CARD_MINIMAL_TIME 5 */
/* #  define CONFIG_RESET_BETWEEN_POLL_MS 5 */
/* #  define CONFIG_TICKLESS */

// Disabled features (order by alphabet)
#  undef CONFIG_API_POLLING_TIME_AS_INPUT_2BYTE
//#  undef CONFIG_DEBUG_PRINT_SLEEP_INTERVAL_MS // Fix_UIPara_v2000 vike.2017_09_18
#  undef CONFIG_DEBUG_PRINT_TICK_INTERVAL_MS  // Fix_UIPara_v2000 vike.2017_09_18
#  undef CONFIG_DEBUG_PRINT_NOT_DLE  // Fix_UIPara_v2000 vike.2017_09_18
#  undef CONFIG_FUN_SERVICE_INFO    //營運參數.端末設備狀態.function. // Fix_UIPara_v2000 vike.2017_09_18
#  undef CONFIG_DEBUG_READ_SYS_REC
#  undef CONFIG_DEBUG_SNEAK_OUT_IP // "192.168.1.1"
#  undef CONFIG_DEBUG_SNEAK_OUT_PORT // 40000
#  undef CONFIG_END_TRANSACTION
#  undef CONFIG_FILESYSTEM_OP
//#  undef CONFIG_FLASH_IO_BY_ADDR
#  undef CONFIG_GET_RF_MODULE_INFO
#  undef CONFIG_GET_SAM_SLOT
#  undef CONFIG_GET_TICKS_COUNT_10MS
#  undef CONFIG_GET_TX_LOG2
#  undef CONFIG_INT_TYPES_HOME_MADE
#  undef CONFIG_MIFARE_RETRY_COUNT
#  undef CONFIG_READER_SHUTDOWN
#  undef CONFIG_REFUND_DECREMENT_DAILY_ACCUMULATE
#  undef CONFIG_SOFTWARE_DES
#  undef CONFIG_TICKLESS
#  undef CONFIG_TIME_H_STDLIB
#  undef CONFIG_TRANSLATE_RETURN_CODE_SWITCH_CASE
#  undef CONFIG_WINDOWS

#endif
